version: "3"
services:
  app:
    image: my-repo:latest
    hostname: my-repo
    build:
      context: .
      #dockerfile: Dockerfile_Fastapi
      dockerfile: Dockerfile_Streamlit
    ports:
      - 5000:5000
    container_name: my-repo