FROM python:3.8
RUN apt-get clean -y && apt-get update -y && apt-get install bash
RUN pip install --upgrade pip 
EXPOSE 5000
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]

